language: node_js
node_js:
  - "9"
cache:
    directories:
     - node_modules
script:
    - npm test
env:
    - CI=false
    - REACT_APP_API_BASE_URL=https://peaceful-garden-13000.herokuapp.com/
before_deploy:
    - npm install netlify-cli -g
    - npm ci

deploy:
    provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
    skip_cleanup: true
    on:
        branch: master
